; segment on
extern segment_0_on, segment_1_on, segment_2_on, segment_3_on, segment_4_on
extern segment_5_on, segment_6_on, segment_7_on, segment_8_on, segment_9_on

extern segment_10_on, segment_11_on, segment_12_on, segment_13_on, segment_14_on
extern segment_15_on, segment_16_on, segment_17_on, segment_18_on, segment_19_on

extern segment_20_on, segment_21_on, segment_22_on, segment_23_on, segment_24_on
extern segment_25_on, segment_26_on, segment_27_on, segment_28_on, segment_29_on

extern segment_30_on, segment_31_on, segment_32_on, segment_33_on, segment_34_on
extern segment_35_on, segment_36_on, segment_37_on, segment_38_on, segment_39_on

extern segment_40_on, segment_41_on, segment_42_on, segment_43_on, segment_44_on
extern segment_45_on, segment_46_on, segment_47_on, segment_48_on, segment_49_on

extern segment_50_on, segment_51_on, segment_52_on, segment_53_on, segment_54_on


; segment off
extern segment_0_off, segment_1_off, segment_2_off, segment_3_off, segment_4_off
extern segment_5_off, segment_6_off, segment_7_off, segment_8_off, segment_9_off

extern segment_10_off, segment_11_off, segment_12_off, segment_13_off, segment_14_off
extern segment_15_off, segment_16_off, segment_17_off, segment_18_off, segment_19_off

extern segment_20_off, segment_21_off, segment_22_off, segment_23_off, segment_24_off
extern segment_25_off, segment_26_off, segment_27_off, segment_28_off, segment_29_off

extern segment_30_off, segment_31_off, segment_32_off, segment_33_off, segment_34_off
extern segment_35_off, segment_36_off, segment_37_off, segment_38_off, segment_39_off

extern segment_40_off, segment_41_off, segment_42_off, segment_43_off, segment_44_off
extern segment_45_off, segment_46_off, segment_47_off, segment_48_off, segment_49_off

extern segment_50_off, segment_51_off, segment_52_off, segment_53_off, segment_54_off


; tables
extern table_space
extern table_a, table_b, table_c, table_d, table_e, table_f, table_g, table_h, table_i
extern table_j, table_k, table_l, table_m, table_n, table_o, table_p, table_q, table_r
extern table_s, table_t, table_u, table_v, table_w, table_x, table_y, table_z
extern table_0, table_1, table_2, table_3, table_4, table_5, table_6, table_7, table_8
extern table_9
extern table_tateti
