extern segment_0_on, segment_1_on, segment_2_on, segment_3_on, segment_4_on
extern segment_5_on, segment_6_on, segment_7_on, segment_8_on, segment_9_on

extern segment_10_on, segment_11_on, segment_12_on, segment_13_on, segment_14_on
extern segment_15_on, segment_16_on, segment_17_on, segment_18_on, segment_19_on

extern segment_20_on, segment_21_on, segment_22_on, segment_23_on, segment_24_on
extern segment_25_on, segment_26_on, segment_27_on, segment_28_on, segment_29_on

extern segment_30_on, segment_31_on, segment_32_on, segment_33_on, segment_34_on
extern segment_35_on, segment_36_on, segment_37_on, segment_38_on, segment_39_on

extern segment_40_on, segment_41_on, segment_42_on, segment_43_on, segment_44_on
extern segment_45_on, segment_46_on, segment_47_on, segment_48_on, segment_49_on

extern segment_50_on, segment_51_on, segment_52_on, segment_53_on, segment_54_on
